/**
 * CSCI 221, HW 2 (McCauley)
 * Base code provided by instructor and updated by:
 * 
 * Julie Yib 
 */

import java.util.*;
import java.io.*;
import java.awt.*;

public class MapDataDrawer
{
  // store map data in grid array
  private int[][] grid; 
  
  // Read 2D array into grid. Data in file "filename", grid is rows x cols
   public MapDataDrawer(String filename, int rows, int cols) throws Exception{
      // initialize grid 
      grid = new int[rows][cols];
      //read the data from the file into the grid
      Scanner S = new Scanner(new File(filename));    
      
       for(int row=0; row < grid.length; row++){
          for(int col=0; col<grid[0].length; col++){
             grid[row][col] = S.nextInt(); 
          }
       }
      
  }

  
  /**
   * @return the min value in the entire grid
   */
  public int findMin(){
      int findMin = 2000;
        for (int row = 0; row < grid.length; row++) {
          for (int col = 0; col < grid[0].length; col ++){
              if (grid[row][col] < findMin){
                 findMin = grid[row][col];
                }
            }
        }
      return findMin;  
  }
  
  /**
   * @return the max value in the entire grid
   */
  public int findMax(){
      int findMax = 0;
        for (int row = 0; row < grid.length; row++) {
          for (int col = 0; col < grid[0].length; col ++){
              if (grid[row][col] > findMax){
                 findMax = grid[row][col];
                }
            }
        }
      return findMax; 
  }
  
  /**
   * @param col the column of the grid to check
   * @return the index of the row with the lowest value in the given col for the grid
   */
  public  int indexOfMinRow(int col){
      int indexOfMinRow = 0;
      int minR = 0;
      int row = 0;
      int minC = 0;
        for (row = 0; row < grid.length; row++) {
            if (grid[row][col] < indexOfMinRow){
                 indexOfMinRow = grid[row][col];
                 minR = row;
                 minC = col;
                }
        }   
      return minR;  
  }
  
  
  /**
   * DON'T CHANGE THIS CODE
   * Draws the grid using the given Graphics object. 
   * Colors should be grayscale values 0-255, scaled based on min/max values in grid
   * 
   * ALERT:Until your findMin and findMax methods work, your output will
   * be a completely black graph.
   */
  public void drawMap(Graphics g){
      
    int minVal = findMin();
    int maxVal = findMax();
    double range = maxVal - minVal;
    
    for(int row=0; row < grid.length; row++){
      for(int col=0; col<grid[0].length; col++){
         int val = (int)(((grid[row][col]-minVal)/range) * 255);
         //g.setColor(new Color(val,255-val,255-val));
         g.setColor(new Color(val,val,val));
         g.fillRect(col,row,1,1);
        }
    }      
  }
  

   /**
   * Find a path from West-to-East starting at given row.
   * Choose a foward step out of 3 possible forward locations, using greedy method described in assignment.
   * @return the total change in elevation traveled from West-to-East
   */
  public int drawLowestElevPath(Graphics g, int row){
    int currY = row; // row in grid of step one
    // draw initial step - column 0, current row (sent in as parameter)
    g.fillRect(0,row,1,1);

    // Code to compute next step
    int pos = grid[row][0];

    // draw next step where x is currently column and currY is row in grid
    int x = 0; // the value of x will be generated by a loop that goes through the
    // columns, but for now, need something to put in "paint" statement
    for (x = 1; x < grid[x].length; x++){  
        int left = grid[currY -1][x] - pos;
        int fwd = grid[currY][x] - pos ;
        int right = grid[currY +1][x] - pos;
        Math.abs(left);
        Math.abs(fwd);
        Math.abs(right);
        if (left < fwd && left < right){
            g.fillRect(x,(currY-1),1,1);
        }
        if (fwd <= left && fwd <= right){
            g.fillRect(x,currY,1,1);
        }
        if (right < left && right < fwd){
            g.fillRect(x,(currY+1),1,1);
        }
        else {
            g.fillRect(x,(currY+1),1,1);
        }
    }
    
    
    g.fillRect(x,currY,1,1);
    
    return 0; // computed change in elevation
  }
  
  /**
   * @return the index of the starting row for the lowest-elevation-change path in the entire grid.
   */
  public int indexOfLowestElevPath(Graphics g){
      int findMin = 2000;
        for (int row = 0; row < grid.length; row++) {
          for (int col = 0; col < grid[0].length; col ++){
              if (grid[row][col] <= findMin){
                 findMin = grid[row][col];
                 g.fillRect(col,row,1,1);
                }
              
            }
        }
      return 0; // row of path with lowest elevation
  
  }
  
  
}