# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8fcbe5099fffeb91d8340386161e7d013560a44b55d66f3999aebb77fff5204ace8af03ccea7a7c1be0f78d5a33b03419a4c10e0879aa84573930d499845d589

test:
  secret_key_base: c86c8247f216141475a545c65e513cd4dfe241e26b9ff69fe2a949f341f39904e7731679b3839344fd9387a2d1cd632a8448f277bea2b3fb24f69186ddf610f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
