# Generated by Django 2.1.1 on 2018-10-21 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_group', '0002_mycustomusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycustomusers',
            name='user_email',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
