# Generated by Django 2.1.1 on 2018-10-21 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_group', '0003_mycustomusers_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycustomusers',
            name='user_address',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='mycustomusers',
            name='user_exclusions',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='mycustomusers',
            name='user_phone',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='mycustomusers',
            name='user_status',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='mycustomusers',
            name='user_email',
            field=models.EmailField(max_length=128, null=True),
        ),
    ]
