# Generated by Django 2.1.1 on 2018-10-21 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_group', '0005_auto_20181020_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycustomgroup',
            name='members',
        ),
        migrations.AddField(
            model_name='mycustomgroup',
            name='members',
            field=models.ManyToManyField(to='create_group.myCustomUsers'),
        ),
        migrations.AlterField(
            model_name='mycustomusers',
            name='user_address',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='mycustomusers',
            name='user_exclusions',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='mycustomusers',
            name='user_status',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
